import 'bootstrap/dist/css/bootstrap.css';
import { Montserrat } from "next/font/google";
import '../../public/sass/helper/global.scss';
import '../../public/sass/helper/helper.scss';
import '../../public/sass/helper/base.scss';
import '../../public/sass/helper/reset.scss';
import Header from "./components/header";
import Footer from "./components/footer";
import '@fortawesome/fontawesome-svg-core/styles.css'

const montserrat = Montserrat({ subsets: ["latin"], weight:['100','200','300','400','500','600','700','800','900'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" /></head>
      <body id='pb_scroll' className={montserrat.className}><Header />{children}<Footer /></body>
    </html>
  );
}
